spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: test
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false